Param(
    [Parameter(Mandatory=$True)]
    [string]$botWebchatSecret
)

$ErrorActionPreference = "Stop"

function PostMessage($convId, $userName, $userId, $text) {
    $msg = @{
        "type"="message"
        "text"=$text
        "from" = @{
            "id"=$userId
            "name"=$userName
         }
    } | ConvertTo-Json
    Write-Host "Sending: $text"
    $res=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations/$convId/activities" -Method POST -Body $msg -Headers @{"Authorization" = "Bearer $botWebchatSecret"; "Content-Type" = "application/json"}
}

function performConversation ($question, $answerToAppointmentRequest, $answerToMailRequest) {
    Try {
        $conversationStart=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations" -Method POST -Headers @{"Authorization" = "Bearer $botWebchatSecret"} | ConvertFrom-Json

        $userName="ScriptedUser";
        $convId=$conversationStart.conversationId;
        $myId=(New-Guid);

        PostMessage $convId $userName $myId $question

        Do {
            Write-Host "Getting messages..."
            $messages=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations/$convId/activities" -Headers @{"Authorization" = "Bearer $botWebchatSecret"} | ConvertFrom-Json
            $question=$messages.activities | Where-Object {$_.from.id -ne $myId -and $_.text.EndsWith('?')} | Select-Object -Last 1
        } Until ($question)
            Write-Host "Received: " $question.text
        if ($question.text.Contains("appointment")) {
            PostMessage $convId $userName $myId $answerToAppointmentRequest
            }
            else {
            PostMessage $convId $userName $myId $answerToMailRequest
            }
    }
    Catch {
        Write-Host $_.Exception -ForegroundColor Red
    }
}

performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'yes' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'yes' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'yes' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'yes'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'yes'
performConversation 'What is the best personal loan available?' 'yes' 'no'
performConversation 'The interest is way too high' 'no' 'no'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'yes' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'yes' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'yes'
performConversation 'What is the best personal loan available?' 'no' 'no'
performConversation 'The interest is way too high' 'no' 'no'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'yes' 'yes'
performConversation 'The interest is way too high' 'no' 'no'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'yes' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'no'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'yes'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'yes'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'yes'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'no'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'no' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'yes'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'yes' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'yes' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'yes' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'yes'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'yes' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'yes' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'yes' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'no' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'no' 'yes'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'The student loan plan is terrible?' 'yes' 'yes'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'yes' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
performConversation 'The interest is too high' 'yes' 'no'
performConversation 'What does student loan have as interest?' 'no' 'no'
performConversation 'Why is the credit card entry fee so expensive?' 'yes' 'no'
performConversation 'I need a low interest credit card?' 'yes' 'no'
performConversation 'What is the best personal loan available?' 'no' 'yes'
performConversation 'The interest is way too high' 'no' 'yes'
performConversation 'What is the student loan payments plan?' 'yes' 'no'
performConversation 'Th student loan plan is terrible?' 'no' 'no'
performConversation 'Do you still have a shopping rewards credit card?' 'yes' 'no'
performConversation 'What does the shopping rewards credit card look like?' 'yes' 'no'
performConversation 'The shopping rewards credit card is stupid' 'no' 'no'
performConversation 'Do you still have a travel points credit card?' 'no' 'yes'
performConversation 'What is the interest of the travel points credit card?' 'yes' 'yes'
